name: error handle
on: [pull_request, push, workflow_dispatch]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: exit 1
        run: exit 1
      - name: echo
        run: echo test
