name: Manually development env deploy workflow
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: |
          echo 'ls -la'
          ls -la
          echo 'pwd'
          pwd
          echo 'git'
          git branch
          git rebase master
          ls -la
