name: Manually development env deploy workflow
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: dump github event payload
        env:
          GITHUB_PAYLOAD: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_PAYLOAD"
      - run: |
          set -x
          git fetch
          branch_name=`echo ${{ github.ref }} | sed 's/refs\/heads\///'`
          git fetch origin $branch_name
          git checkout $branch_name --
          git branch --set-upstream-to=origin/$branch_name
          git pull origin master:master
          git rebase master
          ls -la
