name: Manually development env deploy workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name you want to deploy'
        required: true
        default: 'develop'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git checkout ${{ github.event.inputs.name }}
        ls -la
