name: Manually development env deploy workflow
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: dump github event payload
        env:
          GITHUB_PAYLOAD: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_PAYLOAD"
      - run: |
          set -x
          git fetch
          cat .git/HEAD
          git name-rev ${{ github.sha }}
          branch_name=`echo ${{ github.ref }} | sed 's/refs\/heads\///'`
          echo $branch_name
          git branch --remote
          git checkout origin/$branch_name
          cat .git/HEAD
          git branch
          echo 'ls -la'
          ls -la
          echo 'pwd'
          pwd
          echo 'git'
          git branch
          git rebase master
          ls -la
