name: Manually development env deploy workflow
on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'ls -la'
        ls -la
        echo 'pwd'
        pwd
        echo 'cd ..'
        cd ..
        echo 'ls -la'
        ls -la
        echo 'git'
        git branch
